---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        # dest: "/etc/ansible/backups/{{inventory_hostname}}.config"
        
    - local_action:
           module: ftp
           host: 10.16.17.89
           user: ansible
           password: ansible
           src: "{{config_output.backup_path}}"
           dest: /{{inventory_hostname}}.config
           direction: push
